project:
  type: website

website:
  title: "myblog"
  sidebar:
    style: "docked"
    search: true
    contents: auto
  navbar:
    background: light
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pinkocto
format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true
